name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: morteza-karimi-resume-en.tex
          working_directory: english
          args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
